Annotation and hinting for BitbangIO
adafruit/Adafruit_CircuitPython_BitbangIO pull request #23
Opened 2022-08-04 15:42 UTC by tcfranks

2022-08-04 15:45 UTC, tcfranks commented
going back to check my pre-commit process

2022-08-08 17:49 UTC, tekktrik requested changes
Nice usages of `ReadableBuffer` and `WriteableBuffer`!  A few bits of feedback but looks good!

2022-08-08 17:49 UTC, tekktrik commented on adafruit_bitbangio.py
> +    def _check_lock(self) -> Optional[bool]:
Since the possible results of the function are an exception being raised or `True`, the annotation should be `Literal[True]`.

2022-08-08 17:49 UTC, tekktrik commented on adafruit_bitbangio.py
> -    def __init__(self, scl, sda, *, frequency=400000, timeout=1):
It isn't implemented yet, but I'm pretty sure `timeout` will be allowed to be `float`, so let's type annotate it as such.

2022-08-08 17:49 UTC, tekktrik commented on adafruit_bitbangio.py
> +    def writeto(self, address: int, buffer: ReadableBuffer, *, start=0, end=None) -> None:
Looks like it just got missed here, but `start` is `int`, and `end` is `Optional[int]`!

2022-08-08 17:49 UTC, tekktrik commented on adafruit_bitbangio.py
> +        buffer_out: ReadableBuffer,
Excellent!

2022-08-08 17:49 UTC, tekktrik commented on adafruit_bitbangio.py
> +    def _read(self, address: int, length: int) -> ReadableBuffer:
Since `buffer` is set to a `bytearray` specificly, the return should also be as specific as possible, so it should return `byetarray`.

2022-08-08 17:49 UTC, tekktrik commented on adafruit_bitbangio.py
> +    def configure(self, *, baudrate: int = 100000, polarity: Literal[0,1] = 0, phase: Literal[0,1] = 0, bits: int = 8) -> None:
Nice use of `Literal`!  Mind separating the `0` and `1` with spaces (`Literal[0, 1]`)?

2022-08-08 17:56 UTC, tekktrik requested changes
A few additional things that should help resolve the CI issues.

2022-08-08 17:56 UTC, tekktrik commented on adafruit_bitbangio.py
> +    from typing import Optional
Looks like you're missing the `List` import here as well.

2022-08-08 17:56 UTC, tekktrik commented on adafruit_bitbangio.py
> +    from microcontroller import Pin
Based on this import, make sure you're using `Pin` instead of `microcontroller.Pin` in your type annotations!

2022-08-08 20:19 UTC, tcfranks commented
ok, I've lost all ability to black, pylint, pre-commit locally   under windows cmd it appears to be a path problem.  under git bash it just fails silently.   trying to sort it all out, so debugging the final lint issues may take me a while.

2022-08-09 16:48 UTC, tcfranks commented
is there an issue with setup.py?  this error didn't happen before.  I got pylint and black back, and black wanted to reformat adafruit_bitbangio.py, so I with that and the semi clean pylint run (re: question on f-strings) I was hoping it would run.

2022-08-09 17:14 UTC, tekktrik commented
All the libraries underwent migration from using `setup.py` to using `pyproject.toml`.  You can safely delete `setup.py` from your branch (and pull in changes from upstream).

2022-08-09 18:59 UTC, tcfranks commented
> All the libraries underwent migration from using `setup.py` to using `pyproject.toml`. You can safely delete `setup.py` from your branch (and pull in changes from upstream).

ok.  so if i use typing-extensions it only has to go in requirements.txt?  At least that's what it looks like.....

2022-08-09 19:05 UTC, tekktrik commented
Yep yep!  That's one of the nice changes - single place for dependencies.  Since it's required, `requirements.txt` is the place!

2022-08-09 23:23 UTC, tekktrik commented
Looks like a newline is missing in `requirements.txt`!

2022-08-10 14:20 UTC, tcfranks commented
well, duh.  lesson learned, pylint the .txt file changes if  you made any!

2022-08-10 14:35 UTC, tekktrik approved these changes
Looks good to me, thanks!

2022-08-10 14:35 UTC, merged